import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'doc',
        id: 'getting-started/index',
      },
      collapsed: false,
      items: [
        'getting-started/env-overview',
        'getting-started/docker-development',
        'getting-started/local-development',
        'getting-started/local-deploy',
        'getting-started/logging',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: { type: 'doc', id: 'api/API' },  // Ensures API Reference behaves like a category
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Authenticate Management',
          link: { type: 'doc', id: 'api/auth/auth-introduction' },
          items: [
            'api/auth/signup',
            'api/auth/login',
          ],
        },
        {
          type: 'category',
          label: 'Applications Management',
          link: { type: 'doc', id: 'api/apps/app-introduction' },
          items: [
            'api/apps/create',
            'api/apps/list-apps',
            'api/apps/update-app',
            'api/apps/delete',
            'api/apps/upload',
            // 'api/apps/get-all',
            'api/apps/search',
            'api/apps/update-specific-version-app',
            'api/apps/delete-specific-version-app',
            'api/apps/delete-specific-artifact',
            'api/apps/download',
          ],
        },
        {
          type: 'category',
          label: 'Channels Management',
          link: { type: 'doc', id: 'api/channels/channel-introduction' },
          items: [
            'api/channels/create',
            'api/channels/get',
            'api/channels/update',
            'api/channels/delete',
          ],
        },
        {
          type: 'category',
          label: 'Platforms Management',
          link: { type: 'doc', id: 'api/platforms/platform-introduction' },
          items: [
            'api/platforms/create',
            'api/platforms/get',
            'api/platforms/update',
            'api/platforms/delete',
          ],
        },
        {
          type: 'category',
          label: 'Architectures Management',
          link: { type: 'doc', id: 'api/archs/arch-introduction' },
          items: [
            'api/archs/create',
            'api/archs/get',
            'api/archs/update',
            'api/archs/delete',
          ],
        },
        {
          type: 'category',
          label: 'Users Management',
          link: { type: 'doc', id: 'api/team/users-introduction' },
          items: [
            'api/team/create',
            'api/team/list',
            'api/team/update',
            'api/team/delete',
            'api/team/updateAdmin',
          ],
        },
        {
          type: 'category',
          label: 'Status',
          link: { type: 'doc', id: 'api/info/info-introduction' },
          items: [
            'api/info/latest',
            'api/info/squirrel-windows',
            'api/info/health',
            'api/info/fetch-latest-build',
            'api/info/whoami',
          ],
        },
      ],
    },
    'performance',
    'team_based_auth',
    'telemetry',
    'intermediate_build', 
    'updaters',
    'troubleshooting',
  ],
};

export default sidebars;
